version: '3.8'

services:
  crichattric:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CRICKET_API_KEY=${CRICKET_API_KEY}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - crichattric-network

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - crichattric
    networks:
      - crichattric-network

networks:
  crichattric-network:
    driver: bridge
